### ISSUE TITLE
TypeError: personalization.toJSON is not a function

### ISSUE THREAD

**Issue by frzkhan** [Cellarise/loopback-connector-sendgrid#33]
Im using the following config to send email verification in loopback, which results in this error
works fine with previous version
Not working on ^2.2.4
Working on ^2.1.3

`const options = {
      type: 'email',
      to: 'test@local.email,
      from: 'test@local.email',
      subject: 'subject',
      text: '-',
      html: '-',
      sendGridConfig: {
        personalizations: [{
          to: [{ email: 'test@local.email' }],
          substitutions: {
            '-test-': 'test',
          },
        }],
        templateId: 'sendgridtemplateId'
      }
    }`

**Comment by bravodavid56** [comment]
Leaving this here as a possible solution for others: 

You can try sending a request to the mail/send endpoint of Sendgrid via Postman, with the 'options' object in the body of the request. In your case, 
`{
      type: 'email',
      to: 'test@local.email,
      from: 'test@local.email',
      subject: 'subject',
      text: '-',
      html: '-',
      sendGridConfig: {
        personalizations: [{
          to: [{ email: 'test@local.email' }],
          substitutions: {
            '-test-': 'test',
          },
        }],
        templateId: 'sendgridtemplateId'
      }
    }`

After I ran that, I got an error message saying `"message": "The template_id is required when using dynamic templates"`, so I replaced `templateId` with `template_id` and that worked for me.
